export default {
  products: [
    {
      _id: 1,
      name: 'Slim Shirt',
      category: 'Clothing',
      image: '/images/b1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: 2,
      name: 'Cargo Short',
      category: 'Clothing',
      image: '/images/c1.jpg',
      price: 80,
      brand: 'Wrangler',
      rating: 4.8,
      numReviews: 9,
    },
    {
      _id: 3,
      name: 'T Shirt',
      category: 'Clothing',
      image: '/images/d1.jpg',
      price: 45,
      brand: 'Diesel',
      rating: 4.5,
      numReviews: 20,
    },
    {
      _id: 4,
      name: 'Cap',
      category: 'Accessories',
      image: '/images/k1.jpg',
      price: 20,
      brand: 'Van Dotch',
      rating: 5,
      numReviews: 20,
    },
  ],
};
